version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Docker images for backend and frontend..."
      - docker build -t godwin-backend ./backend
      - docker build -t godwin-frontend ./frontend
      - echo "Pushing images to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <your_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker tag godwin-backend:latest <your_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/godwin-backend:latest
      - docker tag godwin-frontend:latest <your_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/godwin-frontend:latest
      - docker push <your_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/godwin-backend:latest
      - docker push <your_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/godwin-frontend:latest

artifacts:
  files:
    - '**/*'
